# Generated by Django 5.2.6 on 2025-09-07 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_alter_college_name_alter_registration_event_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='eventapp.registration'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='registration',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='eventapp.registration'),
        ),
    ]
